### ISSUE TITLE
Graph window cutting off info

### ISSUE THREAD

**Issue by Swisschalet** [andythorne/magurokun-issues#1]
This is an awesome analytics site! One thing i did notice was the graph will cut off the info window when you select a curve. I don't know if theres an option but it would be nice to see specific info on the curve you hover over instead of the total for that day because the colours mesh a bit, maybe when mouse hovers over empty space it lists totals instead. 

https://imgur.com/a/WEQLgg6

Other than that, this is a really handy site and really well done!

**Comment by andythorne** [comment]
Ah yes, it looks like the overflow is being hidden, I'll get a fix out for this asap! Thanks for the report!

**Comment by andythorne** [comment]
This has been fixed! Thanks for the report!
