### ISSUE TITLE
Columns not Resizable

### ISSUE THREAD

**Issue by sgalizia** [andythorne/magurokun-issues#10]
Looks like the columns for the table on Data Query page may have been missed as they are not resizable! Image below to show where:

![image](https://user-images.githubusercontent.com/1574010/79788889-31fa1b00-82fe-11ea-8cef-1ef13d855967.png)

**Comment by andythorne** [comment]
This table is utter trash atm I'm afraid 😂, it was only thrown in at the last minute as an MVP. I've got a work in progress to replace it with a way more detailed version like in the item summary, as well as adding options to include things like min/man/mean sells and buys, profit difference and quantities into the chart!

**Comment by sgalizia** [comment]
That sounds awesome!! I can't wait to see what that looks like :) keep the updates coming! Also I tried to get you some more traffic by posting about your app in r/woweconomy

**Comment by andythorne** [comment]
Ah that's fantastic! Thanks!

**Comment by andythorne** [comment]
This can be done in the improved DataQuery tool update as of 2020/05/02!
