### ISSUE TITLE
Daily Summary Incorrect

### ISSUE THREAD

**Issue by sgalizia** [andythorne/magurokun-issues#12]
The Daily Summary is showing the data for the previously viewed item. Picture below to show what I mean. you can see that the graph and heatmap do not line up with the daily summary

![image](https://user-images.githubusercontent.com/1574010/79797065-75a75180-830b-11ea-8dbc-a10b47ff39da.png)

**Comment by andythorne** [comment]
This should be fixed now! Thanks!
