### ISSUE TITLE
Bug: TSM Group suggestion get stuck

### ISSUE THREAD

**Issue by sgalizia** [andythorne/magurokun-issues#13]
The filter for groups gets stuck if it makes a suggestion and you don't click on one. Escape does not close it either. Only way to close it was to go in and type nonsense so that no suggestions popped up.

![image](https://user-images.githubusercontent.com/1574010/79803787-865dc480-8317-11ea-9a1f-36890a51a5f0.png)

**Comment by andythorne** [comment]
Should be closable by clicking outside the dropdown of pressing escape now! Thanks!
