### ISSUE TITLE
Bug: Clicking on a Saved Query Doesn't Update

### ISSUE THREAD

**Issue by sgalizia** [andythorne/magurokun-issues#14]
I have selected a query that I created and the page does not update to reflect the selected query. In the image below, it should only be showing the sales for the past week, but shows the entire month which is not the query.

![image](https://user-images.githubusercontent.com/1574010/79813913-cf227700-8331-11ea-9489-a4520d824a3d.png)

**Comment by andythorne** [comment]
Fixed! Thanks again! 🙌
