### ISSUE TITLE
Bug: DataQuery filter for one day shows incorrect data in table

### ISSUE THREAD

**Issue by sgalizia** [andythorne/magurokun-issues#15]
I was trying to view the sales for just a single day, the 18th, and set the date filter to start and end on the 18th. In the picture you can see everything seems correct except that the sales data in the table is for the 17th. The graph showed nothing as well which is odd, but that could be because the table data is incorrect.

![image](https://user-images.githubusercontent.com/1574010/79888306-43502f80-83b1-11ea-8753-fef2e1518add.png)

**Comment by andythorne** [comment]
Found the bug! Bloody timezones, the bane of my life 😭 Fix incoming!

**Comment by andythorne** [comment]
Fixed! Thanks!
