### ISSUE TITLE
Groups Not Importing

### ISSUE THREAD

**Issue by sgalizia** [andythorne/magurokun-issues#2]
I have tried importing all of my groups and it errored I think because the string was too long. I tried uploading in smaller groups, but when the import of the groups is 'finished' nothing shows up in the group sections. I also don't see them in the Data Query section. Loving the app so far but would love to be able to see sales based on my groups!!

**Comment by andythorne** [comment]
Thanks for the report and sorry you're experiencing issues! I'll take a look at the logs and see if I can see what happened

**Comment by andythorne** [comment]
That's interesting, it's failed to deserialise _any_ data from the import string. Would you mind sharing with me the import string you used?

**Comment by sgalizia** [comment]
yeah sure! It is pretty large so I will probably try and dump it into a gist and then link it here. And no worries with the issues! Always bugs with new stuff :) I just appreciate you building something like this and offering it for free. So glad to help track it down. I'll come back and link the gist here once it is up. It takes the TSM app a while to process the string. I might even just do a small selection of groups to make this a bit easier.

**Comment by andythorne** [comment]
Ah I see, this string is just the groups part of the export. The deserializer is expecting the entire export generated by the in-game addon. I'll add in a condition so you can import with just a group string!

**Comment by sgalizia** [comment]
Awesome! Looking forward to testing this out. When should I try it on the site again?

**Comment by andythorne** [comment]
@sgalizia I've just deployed it, have a go now!

**Comment by sgalizia** [comment]
Hmm still having issues. I relogged, refreshed the page a few times and then tried uploading a single group again. It was not successful in uploading. I still have no rows under the groups section. Is there anything else I can do to help you track this down?

**Comment by andythorne** [comment]
They should be there now, I can see the import has run and didn't error. When you upload group strings and tsm data they're added to an import queue, so it can take a few minutes till you see them on the page :)

**Comment by sgalizia** [comment]
ohhhh okay I will go take another look!

**Comment by andythorne** [comment]
No problem! Glad we could get it sorted! 🙌
