### ISSUE TITLE
Bug: Negative Numbers on Query Table

### ISSUE THREAD

**Issue by sgalizia** [andythorne/magurokun-issues#22]
Negative numbers on the Query Table have a minus sign in front of each currency: gold, silver, and copper. Should probably just be in front of the gold!

![image](https://user-images.githubusercontent.com/1574010/80856072-98831100-8bfb-11ea-9fbd-ab7e62a630bf.png)

**Comment by andythorne** [comment]
Oh good spot! I'll get that fixed!

**Comment by andythorne** [comment]
Fixed 🎉
