### ISSUE TITLE
Bug: Saved Queries are Gone

### ISSUE THREAD

**Issue by sgalizia** [andythorne/magurokun-issues#23]
Luckily I didn't lose anything too important, but it does look like saved queries were wiped out with the new Data Query updates.

![image](https://user-images.githubusercontent.com/1574010/80856101-d8e28f00-8bfb-11ea-93d2-84236c23bcd8.png)

**Comment by andythorne** [comment]
Unfortunately they weren't transferable to the updated tool so I'm afraid the saved queries have been reset. Sorry!
