### ISSUE TITLE
Bug: 30 Day item summary bar graphs not lining up with dates

### ISSUE THREAD

**Issue by sgalizia** [andythorne/magurokun-issues#26]
The bars and the dates on the graph for the 30 day item query don't really line up. The bars cover the date, but it also looks like they are covering other days? It may just be a scaling issue with the x axis?

![image](https://user-images.githubusercontent.com/1574010/80891058-68c51f00-8c76-11ea-9405-3c62cf25305a.png)

**Comment by andythorne** [comment]
Ah, I see! The "ticks" of the x-axis are not in the centre of the column, that is confusing! I'll get that corrected!

**Comment by andythorne** [comment]
Just released an update that makes this page use the (better) chart from the DataQuery, so this should now be fixed!
