### ISSUE TITLE
Stop emailing me

### ISSUE THREAD

**Issue by declan-m** [andythorne/magurokun-issues#30]
the unsubscribe button doesnt work in the emails.

**Comment by andythorne** [comment]
Thanks @declan-m, there was an issue with the SSL setup on the subscription domain that could affect some users. Should all be fixed now. If you click the link again you should be able to unsubscribe - if it doesn't work first time, you may need to visit https://magurokun.co.uk so your browser detects the changes. Unfortunately, I can't do it myself as it's managed by our email provider, not us!
