### ISSUE TITLE
Bug: Amount cut off on Dashboard

### ISSUE THREAD

**Issue by sgalizia** [andythorne/magurokun-issues#31]
Hey Andy, loving the new Dashboard! One visual issue I am having is that the section with sales has its sale amount per item cut off and the box is not scrollable sideways. I think ideally it should probably scale the text with a size class or something. That is just a suggestion! Otherwise everything else looks awesome! Keep it up :)

![image](https://user-images.githubusercontent.com/1574010/81773217-b0c91a80-949c-11ea-8e99-d76a0310e15d.png)

**Comment by andythorne** [comment]
Hi Sam, thanks! There is a _tiny_ scroll bar at the bottom, but I agree it's not really useful on a desktop. I will increase the breakpoint at which the table wraps below 👍 
![image](https://user-images.githubusercontent.com/1301181/81842164-736b9800-9543-11ea-9980-5ac64e6e180d.png)

**Comment by sgalizia** [comment]
Awesome! Thanks Andy :)

**Comment by andythorne** [comment]
Fixed! :)
