### ISSUE TITLE
"Invalid file format" after importing

### ISSUE THREAD

**Issue by Kaalterak** [andythorne/magurokun-issues#35]
Hey ! 

So i'm not playing so my data ain't really fresh, my csv are from august 2018. After uploading the file, it's goes in the queue, after 1 or 2 min : progress is stuck at 0% and error is "invalid file format".

![image](https://user-images.githubusercontent.com/4558666/83751111-9b43ac80-a666-11ea-8bbb-aa305f7a7a3a.png)

If you want/can fix "old csv" that would be cool, so here's my data. Else i'll stick with my olds scripts, but your ui looks neat :joy:
[Archive.zip](https://github.com/andythorne/magurokun-issues/files/4729613/Archive.zip)

**Comment by andythorne** [comment]
Hey @Kaalterak! I'm the opposite, I only started gold making this year so I only know of the formats since then! I'll take a look and get these older formats working too!

Thanks!

**Comment by andythorne** [comment]
Hey @Kaalterak, turns out this was quite easy to do! If you re-import your logs, they should correctly import! Thanks for raising the issue!
