### ISSUE TITLE
Data Query missing data

### ISSUE THREAD

**Issue by sgalizia** [andythorne/magurokun-issues#4]
There is missing data on the data query. I have sales on the 17th of April (yesterday) but they are not showing on the Data Query.

![image](https://user-images.githubusercontent.com/1574010/79673988-b8461e00-8193-11ea-8abc-47d7ad58d369.png)

In the above shot you can see the data stops on the 16th, but I will post another image below that shows that there are sales on the 17th not showing in the graph:

![image](https://user-images.githubusercontent.com/1574010/79674003-e297db80-8193-11ea-9893-889bcbc37d50.png)

**Comment by andythorne** [comment]
Thanks Sam! I've been able to replicate this and am rolling out a fix atm! A case of `<` instead of `<=`!

**Comment by andythorne** [comment]
Should be fixed now, please reopen if you still see an issue. Thanks for the report again 🙌
