### ISSUE TITLE
Can't upload data

### ISSUE THREAD

**Issue by mjb7569** [andythorne/magurokun-issues#6]
I exported my Sales & Purchases data from the TSM helper app. When attempting to upload to the Magurokun website, it returns an error. Something to do with the size of my data files?

<img width="1594" alt="Screen Shot 2020-04-19 at 9 25 37 AM" src="https://user-images.githubusercontent.com/63964131/79690493-5384d500-8220-11ea-992d-eaa641377de3.png">

**Comment by andythorne** [comment]
Hi @mjb7569, the max upload size is 3mb atm, sorry the error isn't very helpful! Can you try split the files in smaller ones?

**Comment by andythorne** [comment]
@mjb7569 I've just increased the max file size for uploads, have a go uploading now. Please feel free to re-open the ticket if you're still getting an error. Thanks!
