### ISSUE TITLE
Incorrect Data Showing in 30-day Rolling Item Query

### ISSUE THREAD

**Issue by sgalizia** [andythorne/magurokun-issues#7]
I went and looked at the info for selling Enchant - Torrent of Elements, and the summary showed the right title and possible the correct sales data at the bottom, but the graph was definitely wrong. I then went and looked at Battle-Scarred Augment Rune and all of a sudden the graph looks like what I expected for the Enchant info. First picture shows what I saw looking at the runes which is the info for the Enchants. 

![image](https://user-images.githubusercontent.com/1574010/79705720-8d2efd80-826b-11ea-89b9-7bdab137e704.png)

Now when I refresh the page, I see this, which is the correct info for the item I am currently looking at:

![image](https://user-images.githubusercontent.com/1574010/79705765-b0f24380-826b-11ea-9593-6b712f4dbf28.png)

I think the Heatmap info may be correct, but all of the other info seems to be for the item I previously looked at. This is repeatable by looking at an item, click on daily summary, then click on a different item and you should be able to replicate it.

**Comment by andythorne** [comment]
Ekk, not sure how I missed that! I'll get this fixed asap!

**Comment by andythorne** [comment]
Fixed! Thanks for the report!
