### ISSUE TITLE
Columns in Tables Not Resizable

### ISSUE THREAD

**Issue by sgalizia** [andythorne/magurokun-issues#8]
I guess this is more a request for enhancement than a bug. Would like to be able to resize the columns in the table views so I can better read the item names and sale prices and all that. Example below:

![image](https://user-images.githubusercontent.com/1574010/79709179-5a3e3700-8276-11ea-82a5-1cf557a370d0.png)

**Comment by andythorne** [comment]
Yes, I agree, it annoys me too 😂

**Comment by andythorne** [comment]
Turns out this was easy to do! It's live!

**Comment by sgalizia** [comment]
Awesome! Thanks for all your quick responses and fixes! Hope I'm not bugging you with all these reports haha
