### ISSUE TITLE
Clickable Links to 30-Day Rolling Query

### ISSUE THREAD

**Issue by sgalizia** [andythorne/magurokun-issues#9]
Another enhancement that would make exploring data really easy is if you could click on these items in the table and be taken to their 30-day rolling query, example in pic below.

Otherwise I have to go and find it in my daily or weekly sales sections to be able to got to the direct item query.

![image](https://user-images.githubusercontent.com/1574010/79788752-fcedc880-82fd-11ea-81f3-c2a6d817cc19.png)

**Comment by andythorne** [comment]
This can be done in the improved DataQuery tool update as of 2020/05/02!
